#! /bin/sh

$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor LVDS-1 -d I II III IV V VI VII VIII IX X
bspc monitor VGA-1 -d I II III IV V
bspc monitor DP-1 -d VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
